#!/bin/bash

p=$(pwd)

#    -Djava.security.policy=server.policy \
#    -Djava.rmi.server.hostname=localhost \
#    -Dremoting.bind_by_host=false \


java -Djava.rmi.server.codebase=file:///${p}/classes/ \
    -cp lib/javax.servlet-api-3.0.1.jar:lib/mongo-2.7.3.jar:classes \
    edu.harvard.cs262.grading.MongoSubmissionStorageService